# Generated by Django 3.0 on 2020-01-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolistapp', '0002_auto_20200109_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
